//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientSummaryTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatientSummaryTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new patient.
        /// </summary>
        public static string AddPatientButtonTooltip {
            get {
                return ResourceManager.GetString("AddPatientButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new patient.
        /// </summary>
        public static string AddPatientPageTitle {
            get {
                return ResourceManager.GetString("AddPatientPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary for Allergies.
        /// </summary>
        public static string AllergiesIntermediateSummary {
            get {
                return ResourceManager.GetString("AllergiesIntermediateSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for reports.
        /// </summary>
        public static string BrowseReportsButtonText {
            get {
                return ResourceManager.GetString("BrowseReportsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary for Care Plans.
        /// </summary>
        public static string CarePlansIntermediateSummary {
            get {
                return ResourceManager.GetString("CarePlansIntermediateSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary for Conditions.
        /// </summary>
        public static string ConditionsIntermediateSummary {
            get {
                return ResourceManager.GetString("ConditionsIntermediateSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary for Encounters.
        /// </summary>
        public static string EncountersIntermediateSummary {
            get {
                return ResourceManager.GetString("EncountersIntermediateSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary for Imaging Studies.
        /// </summary>
        public static string ImagingStudiesIntermediateSummary {
            get {
                return ResourceManager.GetString("ImagingStudiesIntermediateSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary for Immunizations.
        /// </summary>
        public static string ImmunizationsIntermediateSummary {
            get {
                return ResourceManager.GetString("ImmunizationsIntermediateSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiently manage and access patient records with Contoso Medical. Your dedicated platform for comprehensive clinical oversight..
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary for Medications.
        /// </summary>
        public static string MedicationsIntermediateSummary {
            get {
                return ResourceManager.GetString("MedicationsIntermediateSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLINICAL VIEWS.
        /// </summary>
        public static string NavLabelHeading {
            get {
                return ResourceManager.GetString("NavLabelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary for Observations.
        /// </summary>
        public static string ObservationsIntermediateSummary {
            get {
                return ResourceManager.GetString("ObservationsIntermediateSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading patient details..
        /// </summary>
        public static string PatientDetailsErrorMessage {
            get {
                return ResourceManager.GetString("PatientDetailsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details:.
        /// </summary>
        public static string PatientDetailsTextBoxHeading {
            get {
                return ResourceManager.GetString("PatientDetailsTextBoxHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a patient.
        /// </summary>
        public static string PatientDropdownLabel {
            get {
                return ResourceManager.GetString("PatientDropdownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Patient Lookup.
        /// </summary>
        public static string PatientLookupButtonText {
            get {
                return ResourceManager.GetString("PatientLookupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Lookup.
        /// </summary>
        public static string PatientLookupNavLabel {
            get {
                return ResourceManager.GetString("PatientLookupNavLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get patient details and summary.
        /// </summary>
        public static string PatientPageTitle {
            get {
                return ResourceManager.GetString("PatientPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Records.
        /// </summary>
        public static string PatientRecordsNavLabel {
            get {
                return ResourceManager.GetString("PatientRecordsNavLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading patient summary..
        /// </summary>
        public static string PatientSummaryErrorMessage {
            get {
                return ResourceManager.GetString("PatientSummaryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary:.
        /// </summary>
        public static string PatientSummaryTextBoxHeading {
            get {
                return ResourceManager.GetString("PatientSummaryTextBoxHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error translating patient details..
        /// </summary>
        public static string PatientTranslateErrorMessage {
            get {
                return ResourceManager.GetString("PatientTranslateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary for Procedures.
        /// </summary>
        public static string ProceduresIntermediateSummary {
            get {
                return ResourceManager.GetString("ProceduresIntermediateSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary for Reports.
        /// </summary>
        public static string ReportsIntermediateSummary {
            get {
                return ResourceManager.GetString("ReportsIntermediateSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source language.
        /// </summary>
        public static string SourceLanguageLabel {
            get {
                return ResourceManager.GetString("SourceLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summarize.
        /// </summary>
        public static string SummarizeButtonText {
            get {
                return ResourceManager.GetString("SummarizeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating to English.
        /// </summary>
        public static string TranslationMessage {
            get {
                return ResourceManager.GetString("TranslationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, Healthcare Provider.
        /// </summary>
        public static string WelcomePageTitle {
            get {
                return ResourceManager.GetString("WelcomePageTitle", resourceCulture);
            }
        }
    }
}
